# Generated by Django 3.0.3 on 2020-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='titulo'),
        ),
    ]
